### ISSUE TITLE
Service Generated CSR mode does not return private key so certificate is useless

### ISSUE THREAD

**Issue by tr1ck3r** [Venafi/vcert-java#22] opened 2020-08-25 23:05 UTC
**PROBLEM SUMMARY**
Service Generated CSR mode does not return private key so certificate is useless

**STEPS TO REPRODUCE**
```
certificateRequest = new CertificateRequest().subject(
          new CertificateRequest.PKIXName()
              .commonName("something.venafi.example"))
          .dnsNames(Arrays.asList("san1.venafi.example", "san2.venafi.example))
          .csrOrigin(CsrOriginOption.ServiceGeneratedCSR)  // either ignored or not being handled properly
          .keyType(KeyType.RSA)
          .keyLength(2048); 

certificateRequest = client.generateRequest(zoneConfiguration, certificateRequest);
client.requestCertificate(certificateRequest, zoneConfiguration);

pemCollection = client.retrieveCertificate(certificateRequest);
System.out.println(pemCollection.pemCertificate());
System.out.println(pemCollection.pemPrivateKey());  // shouldn't be null
```

**EXPECTED RESULTS**
`pemCollection.pemPrivateKey()` returns a valid private key when the `csrOrigin` property of the `CertificateRequest` specifies a "ServiceGeneratedCSR"

**ACTUAL RESULTS**
`pemCollection.pemPrivateKey()` always returns null when the `csrOrigin` property of the `CertificateRequest` is set to "ServiceGeneratedCSR"

**Comment by FooBarWidget** [comment] 2020-11-04 09:44
The problem is as follows: the server does include a private key in the RetrieveCertificate response, but it's an encrypted private key. PEMCollection.fromResponse() does not support encrypted private keys.

A fix for this issue will depend on the work already done in https://github.com/Venafi/vcert-java/pull/25, so I'll wait until PR 25 is merged.

**Closed** 2020-11-18 17:09 UTC
Labels: bug
