### ISSUE TITLE
TppTokenConnector.getAccessToken() does not report actual error message sent by server

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-java#47] opened 2021-07-08 12:28 UTC
**PROBLEM SUMMARY**
When `TppTokenConnector.getAccessToken()` fails (because it caches an Unauthorized or BadRequest), it returns a TokenInfo object with errorMessage set to a generic HTTP error message such as "status 400 reading Tpp#authorizeToken(AuthorizeTokenRequest)".

The server's response body contains more details, such as:

~~~json
"{"error":"unauthorized_client","error_description":"User is not authorized to use application 'Fullstaq Jenkins Plugin'"}"
~~~

However, vcert-java does not return this information. This makes troubleshooting hard.

**ENVIRONMENT DETAILS**
Vcert-java 0.6.2.

**Comment by marcos-albornoz** [comment] 2021-09-09 05:02
The issue is already fixed in release [v0.7.1](https://github.com/Venafi/vcert-java/releases/tag/0.7.1). Now the error message contains the server's response body.

**Closed by marcos-albornoz** 2021-09-09 05:02 UTC
Labels: bug
